pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
    }
    stages {
        stage('Example Build') {
            agent { 
                dockerfile {
                filename 'Dockerfile.build'
                dir 'build'
                label 'my-defined-label'
                additionalBuildArgs  '--build-arg version=1.0.2'
                args '-v /tmp:/tmp'
                }
            }
            steps {
                step {
                    echo 'Hello, Maven'
                    s/*h 'mvn --version'*/
                }
            }
        }
        stage('Example Test') {
            when {
                branch 'production'
            }
            agent { docker 'openjdk:8-jre' } 
            steps {
                step{
                    //echo 'Hello, JDK'
                    echo "Hello ${params.PERSON}"
                    sh 'java -version'
                }
            }
        }
    }
    post{
        always{
            
        }
    }
}