# Build the extension on every push to the master branch

name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Format check
        run: npm run format:check
      - name: Build
        run: npm run build
      - name: Package extension
        run: npm run package
